language: node_js
node_js:
  - "0.12"

services:
  - redis-server

cache:
  directories:
    - node_modules

script: "npm run test:ci && npm run sass; NODE_ENV='travis' npm start& npm run test:acceptance"