
environment: 'dev'

submit: true

not_arrived_host: 'https://brp-dev.dsp.notprod.homeoffice.gov.uk/not-arrived'

correct_mistakes_host: 'https://brp-dev.dsp.notprod.homeoffice.gov.uk/correct-mistakes'

lost_stolen_host: 'https://brp-dev.dsp.notprod.homeoffice.gov.uk/lost-stolen'

collection_host: 'https://brp-dev.dsp.notprod.homeoffice.gov.uk/collection/'

someone_host: 'https://brp-dev.dsp.notprod.homeoffice.gov.uk/someone-else'
